name: shedule_And_workflow_Example
on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  ##schedule:
  ## - cron: "*/5 * * * *"
  workflow_dispatch:
  
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: step1 for testing
        run: echo hello world
      - name: step2
        run: |
          echo "hello from step2"
          touch file1
          ls -l 
          pwd
          uname -a
      - run: echo hello from step3 
